import React from "react";
import { useLocation, useNavigate } from "react-router-dom";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import "./InvoicePage.css";

const InvoicePage = () => {
  const location = useLocation();
  const navigate = useNavigate();

  const { formData, invoiceNumber, previousPayments } = location.state;

  const maskCardNumber = (cardNumber) => {
    const lastFour = cardNumber.slice(-4);
    const masked = "*".repeat(cardNumber.length - 4);
    return masked + lastFour;
  };

  const handlePaymentRecordsClick = () => {
    // Create the new payment object
    const newPayment = {
      invoiceNumber,
      name: formData.name,
      email: formData.email,
      cardNumber: formData.cardNumber,
      expiryDate: formData.expiryDate,
      address: formData.address,
      refundStatus: false
    };

    navigate("/payment-records", { 
      state: { 
        userInfo: {
          email: formData.email
        },
        currentPayment: newPayment,
        showUserRecords: true,
        previousPayments
      } 
    });
  };

const downloadPDF = () => {
  const doc = new jsPDF();
  
  // Set header
  doc.setFontSize(22);
  doc.setTextColor("#5940d3");
  doc.text("Invoice", 14, 22);

  // Add a line or decoration
  doc.setLineWidth(0.5);
  doc.setDrawColor("#5940d3");
  doc.line(14, 25, 196, 25); // horizontal line

  // Add table with styling
  autoTable(doc, {
    startY: 35,
    head: [["Field", "Details"]],
    body: [
      ["Name", formData.name],
      ["Invoice Number", invoiceNumber],
      ["Card Number", maskCardNumber(formData.cardNumber)],
      ["Address", formData.address],
    ],
    styles: {
      fontSize: 12,
      cellPadding: 6,
      textColor: "#333",
    },
    headStyles: {
      fillColor: "#5940d3",
      textColor: "#fff",
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: "#f5f5f5",
    },
    margin: { left: 14, right: 14 },
    tableLineColor: "#ddd",
    tableLineWidth: 0.2,
  });

  // Footer
  doc.setFontSize(10);
  doc.setTextColor("#888");
  doc.text("Generated by Care Givers System", 14, doc.internal.pageSize.height - 10);

  doc.save(`Invoice_${invoiceNumber}.pdf`);
};


  return (
    <div className="invoice-container">
      <h2>Payment Successful!</h2>
      <p> 
        Thank you, <strong>{formData.name}</strong>. Your payment was successful.
      </p>
      <p>
        <strong>Invoice Number:</strong> {invoiceNumber}
      </p>
      <p>
        <strong>Card Number:</strong> {maskCardNumber(formData.cardNumber)}
      </p>
      {/*<p>
        <strong>Expiry Date:</strong> {formData.expiryDate}
      </p>*/}
      <p>
        <strong>Address:</strong> {formData.address}
      </p>

      <div className="buttons-container">
        <button onClick={() => navigate("/")}>Insurance</button>   {/*this should change to insurence button*/}
        <button onClick={handlePaymentRecordsClick}>Records</button>
        <button onClick={downloadPDF}>Download PDF</button>
      </div>
    </div>
  );
};

export default InvoicePage;
